sudo: required
dist: trusty

language: python
python:
   - "2.7"

services:
    - docker

before_script:
-  sudo apt-get update
-  sudo apt-get install -y  python-dev python-pip
-  sudo apt-get install -y slony1-2-bin  postgresql-contrib
-  sudo pip install SQLAlchemy

script:
-  env  OMP_NUM_THREADS=4  ./run-all.sh
