sudo: required
dist: trusty

language: python
python:
   - "2.7"

services:
    - docker

before_script:
-  sudo apt-get update
-  sudo apt-get install -y  python-dev python-pip
-  sudo pip install SQLAlchemy

script:
-  ./run-all.sh
